const data = [
    { "title": "Heart Risk Management", "desc": " The Indian heart watch study has revealed the truth behind prevalence, awareness, treatment and control of cardio-vascular disease (CVD) epidemic. This session will educate an elderly person on identifying risks, preventive measures and be aware of treatment modalities along with tips to handle emergencies.","img":"../../assets/img/heart.jpg" },
    { "title": "Diabetes Management", "desc": " According to Research, there were an estimated 40 million persons with diabetes in India in year 2007 and the numbers are steadily increasing. This has resulted in India having the highest economic burden due to diabetes in the world. The session comprises of educating employees on identifying risks, taking preventive measures, lifestyle tips and treatment modalities that help an individual manage diabetes.","img":"../../assets/img/diabetes.jpg" },
    { "title": "Routine Illness Management", "desc": "Routine illnesses like cold, allergies, cough, viral fever and upper respiratory tract infections hamper daily work and performance. It is therefore, imperative to know how to tackle such illnesses get back to your regular routine while the symptoms are subsiding. The session may further include certain home remedies as well.","img":"../../assets/img/illness.jpg"},
    { "title": "Dental Awareness", "desc": "The session will help impart knowledge on oral health awareness.In these particular session the focus will be on oral hygiene, bad breath, oral cancer, tooth sensitivity, oral care.","img":"../../assets/img/dental.jpg" },
    { "title": "Wellness Women", "desc": "The session focuses on health issues faced by women and preventive modalities to manage/tackle the same. The session is designed to include all age groups and address relevant issues.","img":"../../assets/img/women.jpg" },
    { "title": "Stress Management & Positive Lifestyle", "desc": "Stress is a significant by product of our work lifestyle. The best of performances can be vexed by stress and therefore it is imperative for us to learn how to manage and subsequently tackle stress related issues. This session will focus on how elderly person can face stressful situations and turn them around.","img":"../../assets/img/stress.jpg" }

]
export default data;
